### ISSUE TITLE
EDA plugin / rulebooks must be under extensions/eda/event_source and rulebooks

### ISSUE THREAD

**Issue by alisonlhart** [kentik/ansible_eda#1]
EDA structure requires event_source and event_filter plugins to be under an `extensions/eda/event_source` or `extensions/eda/event_filter` respectively, and rulebooks under `extensions/eda/rulebooks`. The collection's EDA plugin is currently located under plugins/event_source/kentik_webhook.py, and rulebooks is in its own dir in the collection root.

The plugin should be moved to `extensions/eda/event_source/kentik_webhook.py` and rulebooks to `extensions/eda/rulebooks`. See EDA docs [here](https://ansible.readthedocs.io/projects/rulebook/en/stable/sources.html#distributing-plugins) for more info.

**Note - if pursuing certification on [Automation Hub](https://console.redhat.com/ansible/automation-hub/):**

This may result in new test failures, since existing test tooling does not evaluate under the extensions/ directory and there is a separate test process for this content. This is subject to change in the future, but currently we use the common python testing tool tox to perform static code analysis with a set of linters.

The linters used for EDA are: pylint, darglint, and ruff. These linters run specifically over the <root>/extensions/eda/plugins dir or deeper. We have built a tox template you can plug into your CI to mimic the tests on Automation Hub. We highly recommend using this template, as some of these linter tests have been deemed irrelevant for certification and are skipped. The link to the templates and documentation is here: https://github.com/ansible/eda-partner-testing

There is additional documentation on the EDA content creation process here: https://redhat-connect.gitbook.io/ansible-eda-content-creation-workflow-guide/

Please reach out to ansiblepartners@redhat.com with any questions! 

Alison, Ansible Partner Engineering Team

**Comment by jryburn** [comment]
@alisonlhart I moved the kentik_webhook.py under `extensions/eda/plugins/event_source` so that the tests with tox will run correctly. Let me know if it needs to go under `extensions/eda/event_source/kentik_webhook.py` and I can do that but then I am confused on how the tox stuff would work.

**Comment by alisonlhart** [comment]
You're correct! My apologies, I wrote that out incorrectly. `extensions/eda/plugins/event_source` etc, is the right structure.
