### ISSUE TITLE
Lint errors

### ISSUE THREAD

**Issue by jryburn** [kentik/ansible_eda#2]
@i3149 I could use another set of eyes if you get a few minutes. I am getting the following lint error when I run tox against my code (coming from darglint):

```extensions/eda/plugins/event_source/kentik_webhook.py:put:141: DAR101: - event```

The code means there is a docstring error but I cannot see any errors in my docstring formatting.

**Comment by alisonlhart** [comment]
@jryburn, I can assist with this. Darglint is saying there's no parameter defined in the docstring for the "event" arg inside the put() function. To fix this, you could do something like: 
```
if __name__ == "__main__":
    # MockQueue is used if running directly
    # via python and not part of an Ansible rulebook.

    class MockQueue:
        """A fake queue."""

        async def put(self: "MockQueue", event: dict) -> None:
            """Print the event.

            Parameters
            ----------
            event : dict
                Event

            """
            print(event)  # noqa: T201

    asyncio.run(
        main(
            MockQueue(),
            {
                "host": "127.0.0.1",
                "port": 5000,
            },
        ),
    )
```

**Comment by jryburn** [comment]
Perfect. Thank you @alisonlhart !
